from typing import Dict, List, Tuple
from temporal.schema import TemporalRelation, Event

class StateTracker:
    """Tracks predicate transitions and full state history per pair.
    
    This is the precursor to Event Extraction (Sprint 4).
    For Sprint 3, it simply stores the TemporalRelations generated by the Aggregator.
    """
    def __init__(self):
        # (subject, object) -> List of TemporalRelations
        self.pair_history: Dict[Tuple[str, str], List[TemporalRelation]] = {}
        
    def add_relations(self, relations: List[TemporalRelation]):
        """Ingest completed relations from the Aggregator."""
        for rel in relations:
            key = (rel.subject_id, rel.object_id)
            if key not in self.pair_history:
                self.pair_history[key] = []
            self.pair_history[key].append(rel)
            
        # Sort each pair's history chronologically
        for key in self.pair_history:
            self.pair_history[key].sort(key=lambda r: r.start_time)

    def get_state_history(self, subject_id: str, object_id: str) -> List[TemporalRelation]:
        return self.pair_history.get((subject_id, object_id), [])
